modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="bendymod"
version="1.0.0"
displayName="Bendy And The Crafting Machine"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="DrLoganblox07, MarceloGToonz, Fredboi, MCreator"
description="Bring the world of the Bendy And The Ink Machine franchise into Minecraft!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.bendymod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.bendymod]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration