
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.bendymod.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.bendymod.block.WritingWhosLaughingNowBlock;
import net.mcreator.bendymod.block.WritingTheCreatorLiedToUsBlock;
import net.mcreator.bendymod.block.WritingDreamsComeTrueBlock;
import net.mcreator.bendymod.block.ValveBlock;
import net.mcreator.bendymod.block.TrashBinBlock;
import net.mcreator.bendymod.block.StudioTiledWallBlock;
import net.mcreator.bendymod.block.StudioPlankedWallBrokenBlock;
import net.mcreator.bendymod.block.StudioPlankedWallBlock;
import net.mcreator.bendymod.block.StudioLampBlock;
import net.mcreator.bendymod.block.StudioFloorStairsBlock;
import net.mcreator.bendymod.block.StudioFloorSlabBlock;
import net.mcreator.bendymod.block.StudioFloorFenceBlock;
import net.mcreator.bendymod.block.StudioFloorBlock;
import net.mcreator.bendymod.block.StudioDoorSegmentedBlock;
import net.mcreator.bendymod.block.StudioDoorBasicBlock;
import net.mcreator.bendymod.block.StudioDirtBlock;
import net.mcreator.bendymod.block.StudioChairBlock;
import net.mcreator.bendymod.block.StudioCeilingBlock;
import net.mcreator.bendymod.block.StudioBrokenFloorBlock;
import net.mcreator.bendymod.block.StudioBricksBlock;
import net.mcreator.bendymod.block.StudioBrickStairsBlock;
import net.mcreator.bendymod.block.StudioBrickSlabBlock;
import net.mcreator.bendymod.block.StudioBlankWallStairsBlock;
import net.mcreator.bendymod.block.StudioBlankWallSlabBlock;
import net.mcreator.bendymod.block.StudioBlankWallFenceBlock;
import net.mcreator.bendymod.block.StudioBlankWallBlock;
import net.mcreator.bendymod.block.SpeakerBlock;
import net.mcreator.bendymod.block.SoupCandleBlock;
import net.mcreator.bendymod.block.SignLightBlock;
import net.mcreator.bendymod.block.SignDarkBlock;
import net.mcreator.bendymod.block.ShelfBlock;
import net.mcreator.bendymod.block.RitualSummoningBlock;
import net.mcreator.bendymod.block.ReelBlock;
import net.mcreator.bendymod.block.RecordBlock;
import net.mcreator.bendymod.block.RadioBlock;
import net.mcreator.bendymod.block.ProjectorBlock;
import net.mcreator.bendymod.block.PosterSheepSongsBlock;
import net.mcreator.bendymod.block.PosterLittleDevilDarlinBlock;
import net.mcreator.bendymod.block.PosterLargeSheepSongsBlock;
import net.mcreator.bendymod.block.PosterLargeLittleDevilDarlinBlock;
import net.mcreator.bendymod.block.PosterLargeDancingDemonBlock;
import net.mcreator.bendymod.block.PosterDancingDemonBlock;
import net.mcreator.bendymod.block.LeverStudioBlock;
import net.mcreator.bendymod.block.LeverPowerBlock;
import net.mcreator.bendymod.block.JumbledPaperBlock;
import net.mcreator.bendymod.block.JDSSignBlock;
import net.mcreator.bendymod.block.InkPuddleWallBlock;
import net.mcreator.bendymod.block.InkPuddleBlock;
import net.mcreator.bendymod.block.InkPipeVerticalBlock;
import net.mcreator.bendymod.block.InkPipeStraightBlock;
import net.mcreator.bendymod.block.InkPipeHorizontalBlock;
import net.mcreator.bendymod.block.InkMachineBlock;
import net.mcreator.bendymod.block.InkBlock;
import net.mcreator.bendymod.block.InkBarrelBlock;
import net.mcreator.bendymod.block.DresserBlock;
import net.mcreator.bendymod.block.DeskFancyBlock;
import net.mcreator.bendymod.block.DeskBlock;
import net.mcreator.bendymod.block.CutoutSinnyBlock;
import net.mcreator.bendymod.block.CutoutBendyBlock;
import net.mcreator.bendymod.block.CrateBlock;
import net.mcreator.bendymod.block.CoffinBlock;
import net.mcreator.bendymod.block.ChainFenceBlock;
import net.mcreator.bendymod.block.CassettePlayerBlock;
import net.mcreator.bendymod.block.BorisCloneBlock;
import net.mcreator.bendymod.block.BoardsBlock;
import net.mcreator.bendymod.block.BendyStatueBlock;
import net.mcreator.bendymod.BendymodMod;

public class BendymodModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, BendymodMod.MODID);
	public static final RegistryObject<Block> STUDIO_BLANK_WALL = REGISTRY.register("studio_blank_wall", () -> new StudioBlankWallBlock());
	public static final RegistryObject<Block> STUDIO_BLANK_WALL_STAIRS = REGISTRY.register("studio_blank_wall_stairs", () -> new StudioBlankWallStairsBlock());
	public static final RegistryObject<Block> STUDIO_BLANK_WALL_SLAB = REGISTRY.register("studio_blank_wall_slab", () -> new StudioBlankWallSlabBlock());
	public static final RegistryObject<Block> STUDIO_BLANK_WALL_FENCE = REGISTRY.register("studio_blank_wall_fence", () -> new StudioBlankWallFenceBlock());
	public static final RegistryObject<Block> STUDIO_PLANKED_WALL = REGISTRY.register("studio_planked_wall", () -> new StudioPlankedWallBlock());
	public static final RegistryObject<Block> STUDIO_PLANKED_WALL_BROKEN = REGISTRY.register("studio_planked_wall_broken", () -> new StudioPlankedWallBrokenBlock());
	public static final RegistryObject<Block> STUDIO_TILED_WALL = REGISTRY.register("studio_tiled_wall", () -> new StudioTiledWallBlock());
	public static final RegistryObject<Block> STUDIO_CEILING = REGISTRY.register("studio_ceiling", () -> new StudioCeilingBlock());
	public static final RegistryObject<Block> STUDIO_FLOOR = REGISTRY.register("studio_floor", () -> new StudioFloorBlock());
	public static final RegistryObject<Block> STUDIO_BROKEN_FLOOR = REGISTRY.register("studio_broken_floor", () -> new StudioBrokenFloorBlock());
	public static final RegistryObject<Block> STUDIO_FLOOR_STAIRS = REGISTRY.register("studio_floor_stairs", () -> new StudioFloorStairsBlock());
	public static final RegistryObject<Block> STUDIO_FLOOR_SLAB = REGISTRY.register("studio_floor_slab", () -> new StudioFloorSlabBlock());
	public static final RegistryObject<Block> STUDIO_FLOOR_FENCE = REGISTRY.register("studio_floor_fence", () -> new StudioFloorFenceBlock());
	public static final RegistryObject<Block> STUDIO_BRICKS = REGISTRY.register("studio_bricks", () -> new StudioBricksBlock());
	public static final RegistryObject<Block> STUDIO_BRICK_STAIRS = REGISTRY.register("studio_brick_stairs", () -> new StudioBrickStairsBlock());
	public static final RegistryObject<Block> STUDIO_BRICK_SLAB = REGISTRY.register("studio_brick_slab", () -> new StudioBrickSlabBlock());
	public static final RegistryObject<Block> STUDIO_DIRT = REGISTRY.register("studio_dirt", () -> new StudioDirtBlock());
	public static final RegistryObject<Block> STUDIO_DOOR_BASIC = REGISTRY.register("studio_door_basic", () -> new StudioDoorBasicBlock());
	public static final RegistryObject<Block> STUDIO_DOOR_SEGMENTED = REGISTRY.register("studio_door_segmented", () -> new StudioDoorSegmentedBlock());
	public static final RegistryObject<Block> CHAIN_FENCE = REGISTRY.register("chain_fence", () -> new ChainFenceBlock());
	public static final RegistryObject<Block> INK = REGISTRY.register("ink", () -> new InkBlock());
	public static final RegistryObject<Block> SIGN_LIGHT = REGISTRY.register("sign_light", () -> new SignLightBlock());
	public static final RegistryObject<Block> SIGN_DARK = REGISTRY.register("sign_dark", () -> new SignDarkBlock());
	public static final RegistryObject<Block> POSTER_LITTLE_DEVIL_DARLIN = REGISTRY.register("poster_little_devil_darlin", () -> new PosterLittleDevilDarlinBlock());
	public static final RegistryObject<Block> POSTER_DANCING_DEMON = REGISTRY.register("poster_dancing_demon", () -> new PosterDancingDemonBlock());
	public static final RegistryObject<Block> POSTER_SHEEP_SONGS = REGISTRY.register("poster_sheep_songs", () -> new PosterSheepSongsBlock());
	public static final RegistryObject<Block> POSTER_LARGE_LITTLE_DEVIL_DARLIN = REGISTRY.register("poster_large_little_devil_darlin", () -> new PosterLargeLittleDevilDarlinBlock());
	public static final RegistryObject<Block> POSTER_LARGE_DANCING_DEMON = REGISTRY.register("poster_large_dancing_demon", () -> new PosterLargeDancingDemonBlock());
	public static final RegistryObject<Block> POSTER_LARGE_SHEEP_SONGS = REGISTRY.register("poster_large_sheep_songs", () -> new PosterLargeSheepSongsBlock());
	public static final RegistryObject<Block> CUTOUT_BENDY = REGISTRY.register("cutout_bendy", () -> new CutoutBendyBlock());
	public static final RegistryObject<Block> PROJECTOR = REGISTRY.register("projector", () -> new ProjectorBlock());
	public static final RegistryObject<Block> DESK = REGISTRY.register("desk", () -> new DeskBlock());
	public static final RegistryObject<Block> STUDIO_CHAIR = REGISTRY.register("studio_chair", () -> new StudioChairBlock());
	public static final RegistryObject<Block> DRESSER = REGISTRY.register("dresser", () -> new DresserBlock());
	public static final RegistryObject<Block> INK_BARREL = REGISTRY.register("ink_barrel", () -> new InkBarrelBlock());
	public static final RegistryObject<Block> STUDIO_LAMP = REGISTRY.register("studio_lamp", () -> new StudioLampBlock());
	public static final RegistryObject<Block> TRASH_BIN = REGISTRY.register("trash_bin", () -> new TrashBinBlock());
	public static final RegistryObject<Block> RADIO = REGISTRY.register("radio", () -> new RadioBlock());
	public static final RegistryObject<Block> SPEAKER = REGISTRY.register("speaker", () -> new SpeakerBlock());
	public static final RegistryObject<Block> CASSETTE_PLAYER = REGISTRY.register("cassette_player", () -> new CassettePlayerBlock());
	public static final RegistryObject<Block> INK_PIPE_HORIZONTAL = REGISTRY.register("ink_pipe_horizontal", () -> new InkPipeHorizontalBlock());
	public static final RegistryObject<Block> INK_PIPE_VERTICAL = REGISTRY.register("ink_pipe_vertical", () -> new InkPipeVerticalBlock());
	public static final RegistryObject<Block> INK_PIPE_STRAIGHT = REGISTRY.register("ink_pipe_straight", () -> new InkPipeStraightBlock());
	public static final RegistryObject<Block> LEVER_POWER = REGISTRY.register("lever_power", () -> new LeverPowerBlock());
	public static final RegistryObject<Block> LEVER_STUDIO = REGISTRY.register("lever_studio", () -> new LeverStudioBlock());
	public static final RegistryObject<Block> VALVE = REGISTRY.register("valve", () -> new ValveBlock());
	public static final RegistryObject<Block> INK_PUDDLE = REGISTRY.register("ink_puddle", () -> new InkPuddleBlock());
	public static final RegistryObject<Block> INK_PUDDLE_WALL = REGISTRY.register("ink_puddle_wall", () -> new InkPuddleWallBlock());
	public static final RegistryObject<Block> INK_MACHINE = REGISTRY.register("ink_machine", () -> new InkMachineBlock());
	public static final RegistryObject<Block> RECORD = REGISTRY.register("record", () -> new RecordBlock());
	public static final RegistryObject<Block> JUMBLED_PAPER = REGISTRY.register("jumbled_paper", () -> new JumbledPaperBlock());
	public static final RegistryObject<Block> BOARDS = REGISTRY.register("boards", () -> new BoardsBlock());
	public static final RegistryObject<Block> BORIS_CLONE = REGISTRY.register("boris_clone", () -> new BorisCloneBlock());
	public static final RegistryObject<Block> BENDY_STATUE = REGISTRY.register("bendy_statue", () -> new BendyStatueBlock());
	public static final RegistryObject<Block> COFFIN = REGISTRY.register("coffin", () -> new CoffinBlock());
	public static final RegistryObject<Block> CRATE = REGISTRY.register("crate", () -> new CrateBlock());
	public static final RegistryObject<Block> WRITING_DREAMS_COME_TRUE = REGISTRY.register("writing_dreams_come_true", () -> new WritingDreamsComeTrueBlock());
	public static final RegistryObject<Block> WRITING_WHOS_LAUGHING_NOW = REGISTRY.register("writing_whos_laughing_now", () -> new WritingWhosLaughingNowBlock());
	public static final RegistryObject<Block> WRITING_THE_CREATOR_LIED_TO_US = REGISTRY.register("writing_the_creator_lied_to_us", () -> new WritingTheCreatorLiedToUsBlock());
	public static final RegistryObject<Block> RITUAL_SUMMONING = REGISTRY.register("ritual_summoning", () -> new RitualSummoningBlock());
	public static final RegistryObject<Block> REEL = REGISTRY.register("reel", () -> new ReelBlock());
	public static final RegistryObject<Block> SOUP_CANDLE = REGISTRY.register("soup_candle", () -> new SoupCandleBlock());
	public static final RegistryObject<Block> CUTOUT_SINNY = REGISTRY.register("cutout_sinny", () -> new CutoutSinnyBlock());
	public static final RegistryObject<Block> DESK_FANCY = REGISTRY.register("desk_fancy", () -> new DeskFancyBlock());
	public static final RegistryObject<Block> SHELF = REGISTRY.register("shelf", () -> new ShelfBlock());
	public static final RegistryObject<Block> JDS_SIGN = REGISTRY.register("jds_sign", () -> new JDSSignBlock());
}
