package net.mcreator.bendymod.block.listener;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.client.event.EntityRenderersEvent;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.mcreator.bendymod.init.BendymodModBlockEntities;
import net.mcreator.bendymod.block.renderer.WritingWhosLaughingNowTileRenderer;
import net.mcreator.bendymod.block.renderer.WritingTheSheepWillComeToSlaughterTileRenderer;
import net.mcreator.bendymod.block.renderer.WritingTheCreatorLiedToUsTileRenderer;
import net.mcreator.bendymod.block.renderer.WritingSingWithMeTileRenderer;
import net.mcreator.bendymod.block.renderer.WritingItsTimeToBelieveTileRenderer;
import net.mcreator.bendymod.block.renderer.WritingIDontWantToWorkHereAnymoreTileRenderer;
import net.mcreator.bendymod.block.renderer.WritingDreamsComeTrueTileRenderer;
import net.mcreator.bendymod.block.renderer.WritingDownHereWereAllSinnersTileRenderer;
import net.mcreator.bendymod.block.renderer.WrenchTileRenderer;
import net.mcreator.bendymod.block.renderer.WrenchRLTileRenderer;
import net.mcreator.bendymod.block.renderer.WorkTableTileRenderer;
import net.mcreator.bendymod.block.renderer.WallGash1TileRenderer;
import net.mcreator.bendymod.block.renderer.ViolinTileRenderer;
import net.mcreator.bendymod.block.renderer.ValveTileRenderer;
import net.mcreator.bendymod.block.renderer.TrashBinTileRenderer;
import net.mcreator.bendymod.block.renderer.ToolboxTileRenderer;
import net.mcreator.bendymod.block.renderer.TastyEatsMachineTileRenderer;
import net.mcreator.bendymod.block.renderer.StudioToiletTileRenderer;
import net.mcreator.bendymod.block.renderer.StudioTVTileRenderer;
import net.mcreator.bendymod.block.renderer.StudioSwitchOnTileRenderer;
import net.mcreator.bendymod.block.renderer.StudioSwitchOffTileRenderer;
import net.mcreator.bendymod.block.renderer.StudioChairTileRenderer;
import net.mcreator.bendymod.block.renderer.StoveTileRenderer;
import net.mcreator.bendymod.block.renderer.SpeakerTileRenderer;
import net.mcreator.bendymod.block.renderer.SoupCandleTileRenderer;
import net.mcreator.bendymod.block.renderer.SofaTileRenderer;
import net.mcreator.bendymod.block.renderer.ShelfTileRenderer;
import net.mcreator.bendymod.block.renderer.SheetHolderTileRenderer;
import net.mcreator.bendymod.block.renderer.ReelTileRenderer;
import net.mcreator.bendymod.block.renderer.ReelBendyDanceTileRenderer;
import net.mcreator.bendymod.block.renderer.RecordingSignTileRenderer;
import net.mcreator.bendymod.block.renderer.RecordTileRenderer;
import net.mcreator.bendymod.block.renderer.RecordRLTileRenderer;
import net.mcreator.bendymod.block.renderer.RadioTileRenderer;
import net.mcreator.bendymod.block.renderer.PunchInCardTileRenderer;
import net.mcreator.bendymod.block.renderer.ProjectorTileRenderer;
import net.mcreator.bendymod.block.renderer.ProjectionTileRenderer;
import net.mcreator.bendymod.block.renderer.PianoTileRenderer;
import net.mcreator.bendymod.block.renderer.PedestalTileRenderer;
import net.mcreator.bendymod.block.renderer.PedestalRLTileRenderer;
import net.mcreator.bendymod.block.renderer.PedestalRLOnTileRenderer;
import net.mcreator.bendymod.block.renderer.PedestalOnTileRenderer;
import net.mcreator.bendymod.block.renderer.MusicDepartmentSignTileRenderer;
import net.mcreator.bendymod.block.renderer.LittleMiracleStationTileRenderer;
import net.mcreator.bendymod.block.renderer.LeverStudioOnTileRenderer;
import net.mcreator.bendymod.block.renderer.LeverStudioOffTileRenderer;
import net.mcreator.bendymod.block.renderer.LeverPowerOnTileRenderer;
import net.mcreator.bendymod.block.renderer.LeverPowerOffTileRenderer;
import net.mcreator.bendymod.block.renderer.LargeBoxTileRenderer;
import net.mcreator.bendymod.block.renderer.JumboBorisDollTileRenderer;
import net.mcreator.bendymod.block.renderer.JumboBendyDollTileRenderer;
import net.mcreator.bendymod.block.renderer.JumbledPaperTileRenderer;
import net.mcreator.bendymod.block.renderer.JDSSignTileRenderer;
import net.mcreator.bendymod.block.renderer.InkMachineTileRenderer;
import net.mcreator.bendymod.block.renderer.InkMachineRLTileRenderer;
import net.mcreator.bendymod.block.renderer.InkBarrelTileRenderer;
import net.mcreator.bendymod.block.renderer.InfermaryBedTileRenderer;
import net.mcreator.bendymod.block.renderer.IndustrialWallPanelTileRenderer;
import net.mcreator.bendymod.block.renderer.IllusionOfLivingTileRenderer;
import net.mcreator.bendymod.block.renderer.IllusionOfLivingRLTileRenderer;
import net.mcreator.bendymod.block.renderer.HeavyGateOpenTileRenderer;
import net.mcreator.bendymod.block.renderer.HeavyGateClosedTileRenderer;
import net.mcreator.bendymod.block.renderer.HatRackTileRenderer;
import net.mcreator.bendymod.block.renderer.HangingMicTileRenderer;
import net.mcreator.bendymod.block.renderer.GentValvesTileRenderer;
import net.mcreator.bendymod.block.renderer.GearshiftTileRenderer;
import net.mcreator.bendymod.block.renderer.GearboxTileRenderer;
import net.mcreator.bendymod.block.renderer.FloorPipeTileRenderer;
import net.mcreator.bendymod.block.renderer.FileCabinetTileRenderer;
import net.mcreator.bendymod.block.renderer.FanTileRenderer;
import net.mcreator.bendymod.block.renderer.DrumTileRenderer;
import net.mcreator.bendymod.block.renderer.DresserTileRenderer;
import net.mcreator.bendymod.block.renderer.DeskTileRenderer;
import net.mcreator.bendymod.block.renderer.DeskOldTileRenderer;
import net.mcreator.bendymod.block.renderer.DeskFancyTileRenderer;
import net.mcreator.bendymod.block.renderer.CutoutSinnyTileRenderer;
import net.mcreator.bendymod.block.renderer.CutoutBendyTileRenderer;
import net.mcreator.bendymod.block.renderer.CoffinTileRenderer;
import net.mcreator.bendymod.block.renderer.Cellbox2TileRenderer;
import net.mcreator.bendymod.block.renderer.Cellbox1TileRenderer;
import net.mcreator.bendymod.block.renderer.Cellbox0TileRenderer;
import net.mcreator.bendymod.block.renderer.CassettePlayerTileRenderer;
import net.mcreator.bendymod.block.renderer.CagedLampTileRenderer;
import net.mcreator.bendymod.block.renderer.BorisDollTileRenderer;
import net.mcreator.bendymod.block.renderer.BorisCloneTileRenderer;
import net.mcreator.bendymod.block.renderer.BookBendyTileRenderer;
import net.mcreator.bendymod.block.renderer.BoardsTileRenderer;
import net.mcreator.bendymod.block.renderer.BendyStatueTileRenderer;
import net.mcreator.bendymod.block.renderer.BendyDollTileRenderer;
import net.mcreator.bendymod.block.renderer.BendyDollRLTileRenderer;
import net.mcreator.bendymod.block.renderer.BendyClockTileRenderer;
import net.mcreator.bendymod.block.renderer.BendyBookStackTileRenderer;
import net.mcreator.bendymod.block.renderer.BassTileRenderer;
import net.mcreator.bendymod.block.renderer.BanjoTileRenderer;
import net.mcreator.bendymod.block.renderer.AliceAngelDollTileRenderer;
import net.mcreator.bendymod.BendymodMod;

@Mod.EventBusSubscriber(modid = BendymodMod.MODID, bus = Mod.EventBusSubscriber.Bus.MOD)
public class ClientListener {
	@OnlyIn(Dist.CLIENT)
	@SubscribeEvent
	public static void registerRenderers(EntityRenderersEvent.RegisterRenderers event) {
		event.registerBlockEntityRenderer(BendymodModBlockEntities.CUTOUT_BENDY.get(), context -> new CutoutBendyTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.CUTOUT_SINNY.get(), context -> new CutoutSinnyTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.INK_MACHINE.get(), context -> new InkMachineTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.SPEAKER.get(), context -> new SpeakerTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.DRESSER.get(), context -> new DresserTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.VALVE.get(), context -> new ValveTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.RECORD.get(), context -> new RecordTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.TRASH_BIN.get(), context -> new TrashBinTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.JUMBLED_PAPER.get(), context -> new JumbledPaperTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.BOARDS.get(), context -> new BoardsTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.RADIO.get(), context -> new RadioTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.CASSETTE_PLAYER.get(), context -> new CassettePlayerTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.DESK.get(), context -> new DeskTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.STUDIO_CHAIR.get(), context -> new StudioChairTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.PROJECTOR.get(), context -> new ProjectorTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.BORIS_CLONE.get(), context -> new BorisCloneTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.BENDY_STATUE.get(), context -> new BendyStatueTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.INK_BARREL.get(), context -> new InkBarrelTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.COFFIN.get(), context -> new CoffinTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.WRITING_DREAMS_COME_TRUE.get(), context -> new WritingDreamsComeTrueTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.WRITING_WHOS_LAUGHING_NOW.get(), context -> new WritingWhosLaughingNowTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.WRITING_THE_CREATOR_LIED_TO_US.get(), context -> new WritingTheCreatorLiedToUsTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.REEL.get(), context -> new ReelTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.SOUP_CANDLE.get(), context -> new SoupCandleTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.DESK_FANCY.get(), context -> new DeskFancyTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.SHELF.get(), context -> new ShelfTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.JDS_SIGN.get(), context -> new JDSSignTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.WORK_TABLE.get(), context -> new WorkTableTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.MUSIC_DEPARTMENT_SIGN.get(), context -> new MusicDepartmentSignTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.GEARBOX.get(), context -> new GearboxTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.TOOLBOX.get(), context -> new ToolboxTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.WRITING_ITS_TIME_TO_BELIEVE.get(), context -> new WritingItsTimeToBelieveTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.WRITING_THE_SHEEP_WILL_COME_TO_SLAUGHTER.get(), context -> new WritingTheSheepWillComeToSlaughterTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.WRITING_SING_WITH_ME.get(), context -> new WritingSingWithMeTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.WRITING_DOWN_HERE_WERE_ALL_SINNERS.get(), context -> new WritingDownHereWereAllSinnersTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.HAT_RACK.get(), context -> new HatRackTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.PUNCH_IN_CARD.get(), context -> new PunchInCardTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.PEDESTAL.get(), context -> new PedestalTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.CELLBOX_0.get(), context -> new Cellbox0TileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.CELLBOX_1.get(), context -> new Cellbox1TileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.CELLBOX_2.get(), context -> new Cellbox2TileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.INFERMARY_BED.get(), context -> new InfermaryBedTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.BENDY_DOLL.get(), context -> new BendyDollTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.WRENCH.get(), context -> new WrenchTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.ILLUSION_OF_LIVING.get(), context -> new IllusionOfLivingTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.HANGING_MIC.get(), context -> new HangingMicTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.SHEET_HOLDER.get(), context -> new SheetHolderTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.BANJO.get(), context -> new BanjoTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.DRUM.get(), context -> new DrumTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.PIANO.get(), context -> new PianoTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.BASS.get(), context -> new BassTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.VIOLIN.get(), context -> new ViolinTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.LARGE_BOX.get(), context -> new LargeBoxTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.HEAVY_GATE_CLOSED.get(), context -> new HeavyGateClosedTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.HEAVY_GATE_OPEN.get(), context -> new HeavyGateOpenTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.LEVER_STUDIO_OFF.get(), context -> new LeverStudioOffTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.LEVER_STUDIO_ON.get(), context -> new LeverStudioOnTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.LEVER_POWER_OFF.get(), context -> new LeverPowerOffTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.LEVER_POWER_ON.get(), context -> new LeverPowerOnTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.RECORD_RL.get(), context -> new RecordRLTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.BENDY_DOLL_RL.get(), context -> new BendyDollRLTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.WRENCH_RL.get(), context -> new WrenchRLTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.ILLUSION_OF_LIVING_RL.get(), context -> new IllusionOfLivingRLTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.PEDESTAL_ON.get(), context -> new PedestalOnTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.PEDESTAL_RL.get(), context -> new PedestalRLTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.PEDESTAL_RL_ON.get(), context -> new PedestalRLOnTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.INK_MACHINE_RL.get(), context -> new InkMachineRLTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.BOOK_BENDY.get(), context -> new BookBendyTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.BENDY_BOOK_STACK.get(), context -> new BendyBookStackTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.REEL_BENDY_DANCE.get(), context -> new ReelBendyDanceTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.WALL_GASH_1.get(), context -> new WallGash1TileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.DESK_OLD.get(), context -> new DeskOldTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.LITTLE_MIRACLE_STATION.get(), context -> new LittleMiracleStationTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.RECORDING_SIGN.get(), context -> new RecordingSignTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.SOFA.get(), context -> new SofaTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.INDUSTRIAL_WALL_PANEL.get(), context -> new IndustrialWallPanelTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.FILE_CABINET.get(), context -> new FileCabinetTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.GENT_VALVES.get(), context -> new GentValvesTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.CAGED_LAMP.get(), context -> new CagedLampTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.FLOOR_PIPE.get(), context -> new FloorPipeTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.PROJECTION.get(), context -> new ProjectionTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.FAN.get(), context -> new FanTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.STUDIO_SWITCH_OFF.get(), context -> new StudioSwitchOffTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.STUDIO_SWITCH_ON.get(), context -> new StudioSwitchOnTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.JUMBO_BENDY_DOLL.get(), context -> new JumboBendyDollTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.BORIS_DOLL.get(), context -> new BorisDollTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.JUMBO_BORIS_DOLL.get(), context -> new JumboBorisDollTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.ALICE_ANGEL_DOLL.get(), context -> new AliceAngelDollTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.STUDIO_TOILET.get(), context -> new StudioToiletTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.STUDIO_TV.get(), context -> new StudioTVTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.TASTY_EATS_MACHINE.get(), context -> new TastyEatsMachineTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.GEARSHIFT.get(), context -> new GearshiftTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.BENDY_CLOCK.get(), context -> new BendyClockTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.STOVE.get(), context -> new StoveTileRenderer());
		event.registerBlockEntityRenderer(BendymodModBlockEntities.WRITING_I_DONT_WANT_TO_WORK_HERE_ANYMORE.get(), context -> new WritingIDontWantToWorkHereAnymoreTileRenderer());
	}
}
